name: Auto-draft PRs missing template

on:
  pull_request:
    types: [opened, reopened]  # https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=ready_for_review#pull_request

jobs:
  missing-template:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      CHECKOUT_DIR: my-repo

    steps:
      - uses: actions/checkout@v5
        with:
          path: ${{ env.CHECKOUT_DIR }}

      - name: Check if the PR template was deleted
        env:
          GH_TOKEN: ${{ github.token }}
        working-directory: ${{ env.CHECKOUT_DIR }}
        run: |
          if ! gh pr view $GITHUB_HEAD_REF --json 'body' | grep -q "Please don't remove this checklist"; then
            gh pr ready $GITHUB_HEAD_REF --undo  # mark as draft
            gh pr edit $GITHUB_HEAD_REF --add-label 'missing-template'
            gh pr review $GITHUB_HEAD_REF --request-changes --body 'Thanks for contributing to the matrix.org website.\n\nI have automatically marked you pull request as a draft. Please restore the [PR template](/.github/pull_request_template.md) to your PR description and follow our [contributing guidelines](/CONTRIBUTING.md), then undraft to let the team know the PR is ready for review.'
          fi
